using UnityEngine;

namespace net.tanngrisnir.stationeers.adiabaticsV2
{
    [AddComponentMenu("Stationeers/Constructors/Constructor")]
    public class Constructor : Assets.Scripts.Objects.Constructor
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM LOGIC.
    }
}
